#!/usr/bin/env python3
"""Generates the glue between the launcher and the game modules.

From games/games.json and the module sizes written by npmodule.py:
- gametable.c: the table of games the launcher shows (np_games);
- arena.s: the RAM arena, and the symbols that place each game's .data and
  .bss inside it (games never run together). It is the last of NumPlay's RAM
  and holds what the launcher needs; a game uses it and the RAM after it, up to
  the end of what the calculator's software gives apps (_heap_end), so NumPlay
  installs with a smaller userland too and a game that doesn't fit there says
  so (launcher/src/games.c). arena_extra: how much more than the arena the
  hungriest game takes, for the Makefile's check of every game's RAM;
- marks.s: a head and a tail word around each game's block of flash;
- numplay.ld: the script of the final `ld -r`, which keeps each game's code,
  data image, screenshots and marks together as one block.

With --only "id id ...", only those games (NumPlay for Upsilon: those that fit its RAM); each keeps
the index of its place in games.json, which its module's sections are named after.

Usage: gen_games.py games.json MODULE_DIR OUT_DIR [--simulator] [--only "id id ..."]
"""
import argparse
import json
import os
import re

LAUNCHER_RAM = 96 * 1024  # the arena's own size; the launcher's screenshot cache takes what there is
HEAD, TAIL = 0x3147504E, 0x444E4550


def c_str(s):
    return "NULL" if s is None else json.dumps(s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest")
    ap.add_argument("modules")
    ap.add_argument("out")
    ap.add_argument("--simulator", action="store_true")
    ap.add_argument("--only", help="space separated game ids")
    a = ap.parse_args()
    games = json.load(open(a.manifest))
    index = {g["id"]: n for n, g in enumerate(games, 1)}
    if a.only:
        keep = a.only.split()
        missing = [i for i in keep if i not in index]
        if missing:
            raise SystemExit(f"--only: no such games: {missing}")
        games = [g for g in games if g["id"] in keep]
    np_h = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "launcher", "src", "np.h")).read()
    limit = int(re.search(r"#define NP_MAX_GAMES (\d+)", np_h).group(1))
    if len(games) > limit:
        raise SystemExit(f"{len(games)} games, but the launcher holds {limit} (NP_MAX_GAMES in launcher/src/np.h)")
    os.makedirs(a.out, exist_ok=True)
    sizes = {}
    for g in games:
        p = os.path.join(a.modules, g["id"] + ".json")
        sizes[g["id"]] = json.load(open(p)) if os.path.exists(p) else {"code": 0, "data": 0, "bss": 0, "ram_align": 8}

    # ---- RAM layout
    need = LAUNCHER_RAM
    layout = {}
    for g in games:
        s = sizes[g["id"]]
        data = s["data"]
        bss_off = (data + 7) & ~7
        layout[g["id"]] = (0, bss_off)
        need = max(need, bss_off + s["bss"])
    need = (need + 7) & ~7
    # (the simulator's arena, a C array, keeps the hungriest game's size)
    arena = need if a.simulator else LAUNCHER_RAM

    # ---- games.c
    L = ["/* Generated by tools/gen_games.py from games/games.json. */", '#include "np.h"', ""]
    for g in games:
        i = g["id"]
        L.append(f"extern const uint32_t np_{i}_begin[], np_{i}_end[];")
        L.append(f"extern uint8_t np_{i}_data[], np_{i}_bss[];")
        L.append(f"extern const uint8_t np_{i}_init[];")
        L.append(f"extern const np_shot_t np_{i}_shots[];")
        L.append(f"int np_{i}_main(void);")
        recs = ", ".join(json.dumps(r) for r in g["records"])
        L.append(f"static const char *const {i}_records[] = {{{recs + ', ' if recs else ''}NULL}};")
        prog = ", ".join(json.dumps(r) for r in g.get("reset", g["records"]))
        L.append(f"static const char *const {i}_progress[] = {{{prog + ', ' if prog else ''}NULL}};")
        L.append("")
    if a.simulator:
        L.append("/* The simulator has no flash blocks and gives each game its own RAM. */")
        for g in games:
            i = g["id"]
            L.append(f"const uint32_t np_{i}_begin[1], np_{i}_end[1];")
        L.append("#define RAM(x) NULL")
        L.append("#define INIT(x) NULL")
        L.append("#define SIZE(x) 0")
        L.append(f"uint8_t np_arena[{arena}] __attribute__((aligned(8)));")
    else:
        L.append("#define RAM(x) x")
        L.append("#define INIT(x) x")
        L.append("#define SIZE(x) x")
    L.append(f"const uint32_t np_arena_size = {arena};")
    L.append("")
    L.append("const np_game_t np_games[] = {")
    for g in games:
        i = g["id"]
        s = sizes[i]
        est = s["code"] + s["data"]
        L.append(f"  {{{c_str(i)}, {c_str(g['title'])}, {c_str(g['tagline'])}, {c_str(g.get('credit'))},")
        L.append(f"   {g['top']}, {g['bottom']}, {g['accent']}, np_{i}_begin, np_{i}_end, np_{i}_main,")
        L.append(f"   RAM(np_{i}_data), INIT(np_{i}_init), SIZE({s['data']}), RAM(np_{i}_bss), SIZE({s['bss']}),")
        L.append(f"   np_{i}_shots, {len(g['shots'])}, {i}_records, {i}_progress, {est}}},")
    L.append("};")
    L.append(f"const int np_game_count = {len(games)};")
    open(os.path.join(a.out, "gametable.c"), "w").write("\n".join(L) + "\n")

    if a.simulator:
        print(f"games: {len(games)} (simulator)")
        return

    # ---- arena.s
    S = ["@ Generated by tools/gen_games.py: one RAM arena shared by the launcher and the games, the",
         "@ last of NumPlay's RAM (numplay.ld): a game goes on into the RAM after it.",
         '  .section .np_arena,"aw",%nobits', "  .balign 8", "  .global np_arena", "np_arena:",
         f"  .space {arena}"]
    for g in games:
        i = g["id"]
        d, b = layout[i]
        S += [f"  .global np_{i}_data", f"  .set np_{i}_data, np_arena + {d}",
              f"  .global np_{i}_bss", f"  .set np_{i}_bss, np_arena + {b}"]
    open(os.path.join(a.out, "arena.s"), "w").write("\n".join(S) + "\n")
    open(os.path.join(a.out, "arena_extra"), "w").write(f"{need - arena}\n")

    # ---- marks.s
    M = ["@ Generated by tools/gen_games.py: the first and last words of each game's block."]
    for g in games:
        i, n = g["id"], index[g["id"]]
        M += [f'  .section .rodata.np.{n}.{i}.0head,"a"', "  .balign 4", f"  .word {HEAD:#x}",
              f'  .section .rodata.np.{n}.{i}.zztail,"a"', "  .balign 4", f"  .word {TAIL:#x}"]
    open(os.path.join(a.out, "marks.s"), "w").write("\n".join(M) + "\n")

    # ---- numplay.ld
    D = ["/* Generated by tools/gen_games.py. Script of the final `ld -r` that makes NumPlay.nwa:",
         "   each game becomes one section, so the calculator's installer keeps its code, data image,",
         "   screenshots and marks in one block of flash that uninstalling can wipe. */",
         "SECTIONS {",
         "  .rodata.eadk_app_name : { KEEP(*(.rodata.eadk_app_name)) }",
         "  .rodata.eadk_api_level : { KEEP(*(.rodata.eadk_api_level)) }",
         "  .rodata.eadk_app_icon : { KEEP(*(.rodata.eadk_app_icon)) }"]
    for g in games:
        i, n = g["id"], index[g["id"]]
        p = f".rodata.np.{n}.{i}"
        D += [f"  {p} : {{",
              f"    np_{i}_begin = .;",
              f"    KEEP(*({p}.0head))",
              f"    *({p})",
              f"    *({p}.init)",
              f"    KEEP(*({p}.shots))",
              f"    KEEP(*({p}.zztail))",
              f"    np_{i}_end = .;",
              "  }"]
    D += ["  .text : { *(.text .text.*) }",
          "  .rodata : { *(.rodata .rodata.*) }",
          "  .data : { *(.data .data.*) }",
          "  .bss : { *(.bss .bss.* COMMON) *(.np_arena) }",
          "  /DISCARD/ : { *(.comment) *(.note*) *(.ARM.exidx*) *(.ARM.extab*) }",
          "}"]
    open(os.path.join(a.out, "numplay.ld"), "w").write("\n".join(D) + "\n")
    print(f"games: {len(games)}, arena {arena} bytes, the hungriest game {need}")


if __name__ == "__main__":
    main()
